name: End-to-End Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Cypress
        run: npm install cypress

      - name: Start Server
        run: npm run start &
        working-directory: apps/web


      - name: Run Cypress Tests
        run: npx cypress run
        working-directory: apps/web
        env:
          CI_BASE_URL: 'http://localhost:3000'

    # Optional: Configure Cypress Dashboard Integration
    # - name: Cypress run
    #   uses: cypress-io/github-action@v2
    #   with:
    #     start: npm start
    #     wait-on: 'http://localhost:3000'
    #     record: true
    #     config: video=false
    #   env:
    #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
